import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HarmonySetup } from "harmony-ai-editor";
import { fonts } from "./fonts";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {process.env.NODE_ENV !== "production" ? (
          <HarmonySetup
            repositoryId="02e2a78e-66ba-4d22-963f-0d4eb218bf2f"
            fonts={fonts}
          />
        ) : null}
      </body>
    </html>
  );
}
